bears_project/bears_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from applications.bears import views as bear_view
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', bear_view.ListBearsView.as_view(), name='bears'),
    url(r'^add-bear$', bear_view.AddBearsView.as_view(), name='add_bear'),
    url(r'^i-love-bears/$', TemplateView.as_view(template_name="bears/i_love_bears.html"),
        name="i_love_bears"),

]

bears_project/applications/bears/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _


class Bear(models.Model):
    """Model, which represents a bear entity.
    :name: Name of the bear.
    :bear_type: Official bear type.
    """
    name = models.CharField(_('Name'), max_length=128, )

    bear_type = models.CharField(_('Name'),max_length=128,choices=(
        ('grizzy', _('Grizzy')),
        ('mini', _('Mini')),
                                                                    ),
    )

bears_project/applications/bears/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, CreateView

from applications.bears.models import Bear


class ListBearsView(ListView):
    """
    list all bears
    """
    model = Bear
    template_name = 'bears/list_bears.html'
    context_object_name = 'bears'

    def get_queryset(self, **kwargs):
        bears = super(ListBearsView, self).get_queryset(**kwargs)
        bears = bears.order_by('bear_type')
        return bears


class AddBearsView(CreateView):
    """
     Create new Bear
    """

    template_name = 'bears/add_bear.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request):
        ctx = {}
        name = request.POST.get('name')
        bear_type = request.POST.get('bear_type')

        if Bear.objects.filter(name=name, bear_type=bear_type).exists():
            #Prevent from creating duplicate entries
            ctx['status'] = False
            ctx['exist'] = True
        else:
            if name and bear_type:
                bear = Bear()
                bear.name = name
                bear.bear_type = bear_type
                bear.save()
                ctx['status'] = True
            else:
                ctx['status'] = False
        if ctx['status'] == True:
            #set cookie if an entry has been created
                response = HttpResponse(json.dumps(ctx), content_type="application/json")
                response.set_cookie('i_love_cookies', 'I love cookies')
                return response
        return HttpResponse(json.dumps(ctx), content_type="application/json")

bears_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
 {% block title %}
 {% endblock title%}
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="{% static 'css/custom.css' %}">

</head>
<body>
  {% block main %}{% endblock %}
</body>
</html>

bears_project/templates/bears/add_bear.html
{% extends "base.html" %}
{% load static %}
{% block title %}
        <head>
	<title>Add Bear</title>
        </head>
        {% endblock %}
{% block main %}


		<!-- contain main informative part of the site -->
		<main id="main">
			<!-- bg block top-->

			<div class="main-hold">
				<!-- contain the main content of the page -->
				<div class="container">
					<div class="registeren-holder">
						
						<!-- inloggen-form -->
						<div class="registeren-box light-gray-bg " style="text-align: center; margin: 100px;">
							<h1 class="headline">Add Bear</h1>
                            <form method="post" novalidate>
                                {% csrf_token %}
                                <div class="form-group">
										<label for="name">Name <span class="form-star">*</span></label>
										<input type="text" class="form-control" id="name"><br>
                                        <span id="span_name" class="errormessage"></span><br>
                                    </div>
									<div class="form-group">
										<label for="bear_type">Bear Type <span class="form-star">*</span></label>
										<select id="bear_type">
                                              <option value="grizzy">Grizzy</option>
                                              <option value="mini">Mini</option>
                                            </select><br>
                                        <span id="span_bear_type" class="errormessage"></span><br>
                                    </div>
									
									
									
									<button type="button" value="Submit" id="create_bear"
                                            class="btn btn-info btn-lg">Submit</button> <br>
                                    <span id="span_success" class="succesmsg"></span><br>
                                    <span id="span_failure" class="errormessage"></span><br>
							</form>
						</div>
					</div>
				</div>
				<!-- bg block bottom-->

			</div>
		</main>
<input type="hidden" id="csrf" value="{{csrf_token}}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
<script src="{% static 'js/custom.js'%}"></script>

{% endblock %}

bears_project/templates/bears/i_love_bears.html
{% extends "base.html" %}

{% block main %}
<h1 style="text-align: center; margin: 100px;">I LOVE BEARS!</h1>
{% endblock %}

bears_project/templates/bears/list_bears.html
{% extends "base.html" %}

{% block main %}
<h1 style="text-align: center; margin: 100px;">BEARS</h1>
        <a href="{% url 'add_bear' %}">Add Bear</a>
        <div >
        {% for bear in bears %}
           <button class="listbear">
               <label class="name">{{ bear.name }}</label> <label class="type">{{ bear.get_bear_type_display }} </label>
           </button><br>
        {% endfor %}
        </div>
{% endblock %}